apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: prometheus
data:
  grafana.ini: |
    [auth.anonymous]
    enabled = true
    org_role = Admin
    
    [auth]
    disable_login_form = true

    [security]
    allow_embedding = true
    cookie_samesite = none
    disable_initial_admin_creation = true