apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: my-raycluster   
  namespace: default   
  labels:
    helm.sh/chart: ray-cluster-1.2.2
    app.kubernetes.io/instance: raycluster
spec:
  rayVersion: "2.9.0"  
  headGroupSpec:
    serviceType: ClusterIP  
    rayStartParams:
      dashboard-host: "0.0.0.0"   
    template:
      metadata:
        labels:
          helm.sh/chart: ray-cluster-1.2.2
          app.kubernetes.io/instance: raycluster
      spec:
        containers:
          - name: ray-head
            image: orin29377053/ray-cluster:latest
            env:
              - name: ROLE
                value: "head" 
            imagePullPolicy: Always 
            resources:
              limits:
                cpu: "2"
                memory: "3G"
              requests:
                cpu: "2"
                memory: "3G"

            volumeMounts:
              - mountPath: /tmp/ray
                name: log-volume 
        volumes:
          - name: log-volume
            emptyDir: {}  
        affinity: {} 
        tolerations: [] 
        nodeSelector: {}  

  workerGroupSpecs:  
    - groupName: workergroup 
      replicas: 1  
      minReplicas: 1 
      maxReplicas: 1 
      rayStartParams: {}
      template:
        metadata:
          labels:
            helm.sh/chart: ray-cluster-1.2.2
            app.kubernetes.io/instance: raycluster
        spec:
          containers:
            - name: ray-worker
              image: orin29377053/ray-cluster:latest  
              env:
                - name: ROLE
                  value: "worker"
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: "2"
                  memory: "6G"
                requests:
                  cpu: "2"
                  memory: "6G"

              volumeMounts:
                - mountPath: /tmp/ray
                  name: log-volume
          volumes:
            - name: log-volume
              emptyDir: {}
          affinity: {}  
          tolerations: []  
          nodeSelector: {}  
