apiVersion: v1
kind: Service
metadata:
  name: ray-head
  namespace: default
spec:
  selector:
    app.kubernetes.io/instance: raycluster
    ray.io/node-type: head
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
    - name: dashboard
      port: 8265
      targetPort: dashboard
  type: ClusterIP